---
title: "MAPA"
author: "Martí Oliver"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
---

Carreguem els paquests necessaris.

```{r}
library(rworldmap)
library(rworldmap)
library(leaflet)
library(leaflet.extras)
library(ggplot2)
library(maps)
```

Creem el primer mapa.

```{r}
dades <- data.frame(
pais <- c("Argentina","Australia","Belgium","Canada","China","Czech Republic","Denmark","France","Germany","Greece","Iceland","India","Iran","Ireland","Italy","Japan","Luxemburg","Netherlands","Norway","Serbia","South Africa","South Korea","Spain","Sewden","United Kingdom","United States"),
lattitude <- c(-38.416097,-25.274398,50.503887,56.130366,35.86166,49.817492,56.26392,46.227638,51.165691,39.074208,64.963051,20.593684,32.427908,53.41291,41.87194,36.204824,          49.815273,52.132633,60.472024,44.016521,-30.559482,35.907757,40.463667,60.128161,55.378051,37.09024),
longitude <- c(-63.616672,133.775136,4.469936,-106.346771,104.195397,15.472962,9.501785,2.213749,10.451526,21.824312,-19.020835,78.96288,53.688046,-8.24389,12.56738,138.252924,               6.129583,5.291266,8.468946,21.005859,22.937506,127.766922,-3.74922,18.643501,-3.435973,-95.712891),
valor <- c(1,13,5,19,1,2,2,2,10,3,1,6,1,3,34,1,1,5,2,1,1,1,12,2,8,54))
mapa <- ggplot() +
  borders("world", fill = "gray80", colour = "white") +
  geom_point(data = dades, aes(x = longitude, y = lattitude, size = valor), color = "red", alpha = 1) +
  labs(title = "Mapa mundial dels països dels investigadors del cens") +
  coord_quickmap()
mapa + ggtitle("Mapa mundial dels països dels investigadors del cens") + xlab("Longitud") + ylab("Latitud")
```

Creem un segon mapa.

```{r}
library(leaflet.extras)
mapa <- leaflet(data = dades) %>%
  addTiles() %>%
  addCircleMarkers(
    lng = ~longitude,
    lat = ~lattitude,
    radius = (valor) ,
    color = "red",
    fillOpacity = 0.1,
    label = ~valor,
    labelOptions = labelOptions(noHide = F)
  )
mapa
```


